-- MySQL Script generated by MySQL Workbench
-- lun 30 oct 2023 13:32:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbStaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbStaff` (
  `idStaff` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `lastName` VARCHAR(120) NOT NULL,
  `hiringDate` DATE NOT NULL DEFAULT CURDATE(),
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idStaff`),
  UNIQUE INDEX `idStaff_UNIQUE` (`idStaff` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbBreeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbBreeds` (
  `idBreed` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `lifeExpectancy` INT NOT NULL,
  `tbBreedscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idBreed`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbDogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbDogs` (
  `idDog` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `size` VARCHAR(12) NOT NULL,
  `photo` VARCHAR(200) NULL,
  `behavior` VARCHAR(45) NOT NULL,
  `yearOfBirth` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(200) NULL,
  `idBreed` INT NOT NULL,
  PRIMARY KEY (`idDog`),
  UNIQUE INDEX `idDogs_UNIQUE` (`idDog` ASC) VISIBLE,
  INDEX `fk_tbDogs_tbBreeds_idx` (`idBreed` ASC) VISIBLE,
  CONSTRAINT `fk_tbDogs_tbBreeds`
    FOREIGN KEY (`idBreed`)
    REFERENCES `mydb`.`tbBreeds` (`idBreed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbTypeOfHousing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbTypeOfHousing` (
  `idTypeOfHousing` INT NOT NULL AUTO_INCREMENT,
  `TypeOfHousingcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypeOfHousing`),
  UNIQUE INDEX `idTypeOfHousing_UNIQUE` (`idTypeOfHousing` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbCandidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbCandidates` (
  `idCandidate` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `lastName` VARCHAR(120) NOT NULL,
  `dni` VARCHAR(8) NOT NULL,
  `yearOfBirth` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(200) NULL,
  `validated` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `idTypeOfHousing` INT NOT NULL,
  PRIMARY KEY (`idCandidate`),
  UNIQUE INDEX `idCandidates_UNIQUE` (`idCandidate` ASC) VISIBLE,
  INDEX `fk_tbCandidates_tbTypeOfHousing1_idx` (`idTypeOfHousing` ASC) VISIBLE,
  CONSTRAINT `fk_tbCandidates_tbTypeOfHousing1`
    FOREIGN KEY (`idTypeOfHousing`)
    REFERENCES `mydb`.`tbTypeOfHousing` (`idTypeOfHousing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbDogsCandidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbDogsCandidates` (
  `idStaff` INT NOT NULL,
  `idDog` INT NOT NULL,
  `idCandidate` INT NOT NULL,
  `adopDate` DATE NOT NULL DEFAULT CURDATE(),
  `comments` VARCHAR(200) NULL,
  PRIMARY KEY (`idStaff`, `idDog`, `idCandidate`),
  INDEX `fk_tbDogsCandidates_tbStaff1_idx` (`idStaff` ASC) VISIBLE,
  INDEX `fk_tbDogsCandidates_tbDogs1_idx` (`idDog` ASC) VISIBLE,
  INDEX `fk_tbDogsCandidates_tbCandidates1_idx` (`idCandidate` ASC) VISIBLE,
  CONSTRAINT `fk_tbDogsCandidates_tbStaff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `mydb`.`tbStaff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbDogsCandidates_tbDogs1`
    FOREIGN KEY (`idDog`)
    REFERENCES `mydb`.`tbDogs` (`idDog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbDogsCandidates_tbCandidates1`
    FOREIGN KEY (`idCandidate`)
    REFERENCES `mydb`.`tbCandidates` (`idCandidate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
