USE biocandb;

INSERT INTO tbBreeds (name, country, size, lifeExpectancy)
VALUES 
('Mil Padres', 'World', 'Every sizes', 12),
('Jack Russell Terrier', 'United Kingdom', 'Small', 16),
('Labrador Retriever', 'United States', 'Large', 12),
('German Shepherd', 'Germany', 'Large', 11),
('Golden Retriever', 'United Kingdom', 'Large', 12),
('French Bulldog', 'France', 'Small', 10),
('Beagle', 'United Kingdom', 'Medium', 13),
('Poodle', 'France', 'Medium', 14),
('Rottweiler', 'Germany', 'Large', 10),
('Yorkshire Terrier', 'United Kingdom', 'Small', 15),
('Boxer', 'Germany', 'Large', 10),
('Dachshund', 'Germany', 'Small', 12),
('Doberman Pinscher', 'Germany', 'Large', 10),
('Siberian Husky', 'Russia', 'Large', 12),
('Great Dane', 'Germany', 'Giant', 8),
('Chihuahua', 'Mexico', 'Small', 15),
('Shih Tzu', 'China', 'Small', 13),
('Pug', 'China', 'Small', 12),
('Bulldog', 'United Kingdom', 'Medium', 10),
('Cocker Spaniel', 'United Kingdom', 'Medium', 12),
('Saint Bernard', 'Switzerland', 'Giant', 10),
('Pomeranian', 'Poland', 'Small', 14),
('Havanese', 'Cuba', 'Small', 13),
('Maltese', 'Malta', 'Small', 14),
('Pekingese', 'China', 'Small', 12),
('Akita', 'Japan', 'Large', 12),
('Bernese Mountain Dog', 'Switzerland', 'Giant', 7),
('Border Collie', 'United Kingdom', 'Medium', 14),
('Bichon Frise', 'France', 'Small', 15),
('Basset Hound', 'France', 'Medium', 11),
('Shetland Sheepdog', 'United Kingdom', 'Small', 13),
('Australian Shepherd', 'United States', 'Medium', 13),
('Alaskan Malamute', 'United States', 'Large', 12),
('Collie', 'United Kingdom', 'Large', 14),
('Weimaraner', 'Germany', 'Large', 12),
('Bullmastiff', 'United Kingdom', 'Giant', 8),
('Bloodhound', 'Belgium', 'Large', 10),
('Newfoundland', 'Canada', 'Giant', 10),
('English Springer Spaniel', 'United Kingdom', 'Medium', 12),
('Italian Greyhound', 'Italy', 'Small', 14),
('Cavalier King Charles Spaniel', 'United Kingdom', 'Small', 12),
('Schnauzer', 'Germany', 'Medium', 13),
('Shiba Inu', 'Japan', 'Small', 13),
('English Bulldog', 'United Kingdom', 'Medium', 10),
('Papillon', 'France', 'Small', 14),
('Chow Chow', 'China', 'Medium', 12),
('Vizsla', 'Hungary', 'Medium', 12),
('Lhasa Apso', 'Tibet', 'Small', 14),
('American Staffordshire Terrier', 'United States', 'Medium', 12),
('Basenji', 'Congo', 'Small', 12),
('Australian Terrier', 'Australia', 'Small', 15),
('Cairn Terrier', 'Scotland', 'Small', 14);

INSERT INTO tbStaff (name, lastName, hiringDate, status) 
VALUES ('Elena', 'Martínez', CURDATE(), 1),
       ('Alejandro', 'García', CURDATE(), 1),
       ('María', 'Fernández', CURDATE(), 0),
       ('Carlos', 'López', CURDATE(), 1),
       ('Laura', 'Rodríguez', CURDATE(), 1);
       
INSERT INTO tbDogs (`name`, `color`, `size`, `photo`, `behavior`, `yearOfBirth`, `comments`, `idBreed`)
VALUES 
('Max', 'Marrón', 'Mediano', 'perro1.jpg', 'Amigable', '2017', 'Juguetón y enérgico', 1),
('Bella', 'Blanco', 'Pequeño', 'perro2.jpg', 'Calmado', '2019', 'Le encanta acurrucarse', 2),
('Charlie', 'Negro', 'Grande', 'perro3.jpg', 'Enérgico', '2018', 'Necesita ejercicio regular', 3),
('Lucy', 'Marrón', 'Mediano', 'perro4.jpg', 'Leal', '2016', 'Genial con los niños', 4),
('Cooper', 'Dorado', 'Grande', 'perro5.jpg', 'Juguetón', '2017', 'Le encantan las actividades al aire libre', 5),
('Luna', 'Gris', 'Mediano', 'perro6.jpg', 'Dócil', '2019', 'Se lleva bien con otras mascotas', 6),
('Oliver', 'Negro y Blanco', 'Pequeño', 'perro7.jpg', 'Inteligente', '2020', 'Aprende rápidamente', 7),
('Mia', 'Marrón', 'Mediano', 'perro8.jpg', 'Animado', '2018', 'Necesita estimulación mental', 8),
('Bailey', 'Dorado', 'Grande', 'perro9.jpg', 'Cariñoso', '2017', 'Disfruta de actividades acuáticas', 9),
('Lola', 'Blanco', 'Pequeño', 'perro10.jpg', 'Curioso', '2019', 'Le encanta explorar nuevos lugares', 10),
('Maximus', 'Negro', 'Mediano', 'perro11.jpg', 'Ansioso por complacer', '2016', 'Responde bien al entrenamiento', 11),
('Zoe', 'Marrón', 'Grande', 'perro12.jpg', 'Dócil', '2018', 'Adorable compañía familiar', 12),
('Coco', 'Blanco y Negro', 'Pequeño', 'perro13.jpg', 'Divertido', '2020', 'Le gusta jugar con juguetes', 13),
('Lucky', 'Marrón', 'Mediano', 'perro14.jpg', 'Leal', '2017', 'Le gusta correr en el parque', 14),
('Milo', 'Gris', 'Pequeño', 'perro15.jpg', 'Cauteloso', '2019', 'Prefiere espacios tranquilos', 15),
('Oscar', 'Negro', 'Grande', 'perro16.jpg', 'Juguetón', '2018', 'Le encanta jugar a buscar', 16),
('Maya', 'Dorado', 'Mediano', 'perro17.jpg', 'Inteligente', '2017', 'Aprende trucos rápidamente', 17),
('Rocky', 'Blanco', 'Grande', 'perro18.jpg', 'Energético', '2016', 'Le gusta nadar', 18),
('Lola', 'Marrón', 'Mediano', 'perro19.jpg', 'Carácter fuerte', '2018', 'Se lleva bien con otros perros', 19),
('Simba', 'Dorado', 'Grande', 'perro20.jpg', 'Leal', '2017', 'Le encanta jugar al aire libre', 20),
('Toby', 'Negro y Blanco', 'Pequeño', 'perro21.jpg', 'Amigable', '2019', 'Adora los mimos', 21),
('Buddy', 'Marrón', 'Mediano', 'perro22.jpg', 'Energético', '2018', 'Le gusta correr y jugar', 22),
('Bailey', 'Blanco', 'Grande', 'perro23.jpg', 'Inteligente', '2017', 'Le encanta resolver rompecabezas', 23),
('Molly', 'Negro', 'Pequeño', 'perro24.jpg', 'Cariñosa', '2019', 'Le gusta dormir en la cama', 24),
('Cody', 'Marrón', 'Mediano', 'perro25.jpg', 'Leal', '2018', 'Es un gran compañero de juego', 25),
('Riley', 'Dorado', 'Grande', 'perro26.jpg', 'Curioso', '2017', 'Explora el mundo con entusiasmo', 26),
('Rosie', 'Negro y Blanco', 'Pequeño', 'perro27.jpg', 'Alegre', '2019', 'Le encanta jugar a la pelota', 27),
('Leo', 'Marrón', 'Mediano', 'perro28.jpg', 'Amigable', '2018', 'Le gusta hacer nuevos amigos', 28),
('Ziggy', 'Gris', 'Grande', 'perro29.jpg', 'Inteligente', '2017', 'Aprende trucos increíbles', 29),
('Luna', 'Blanco', 'Pequeño', 'perro30.jpg', 'Dócil', '2019', 'Le gusta acurrucarse en el sofá', 30);

INSERT INTO tbTypeOfHousing (TypeOfHousingcol)
VALUES 
('Casa propia'),
('Casa de alquiler'),
('Piso propio'),
('Piso de alquiler');

INSERT INTO tbCandidates (name, lastName, dni, yearOfBirth, comments, validated, city, idTypeOfHousing)
VALUES 
('Ainhoa', 'Etxeberria', '12345678A', '1980', 'Prefiere perros grandes', 'Sí', 'Bilbao', 1),
('Unai', 'Zubizarreta', '23456789B', '1982', 'Tiene experiencia con perros pequeños', 'Sí', 'Donostia', 2),
('Leire', 'López', '34567890C', '1985', 'Le encantan los perros de raza mixta', 'No', 'Vitoria-Gasteiz', 3),
('Jon', 'Martínez', '45678901D', '1929', 'Busca un perro activo para hacer ejercicio', 'Sí', 'San Sebastián', 4),
('Maite', 'Ibarra', '56789012E', '1984', 'Desea adoptar un perro de refugio', 'Sí', 'Biarritz', 3),
('Iker', 'Etxeberria', '67890123F', '1981', 'Preferencia por perros jóvenes', 'No', 'Zarautz', 1),
('Amaia', 'Zabala', '78901234G', '1979', 'Interesada en perros entrenados', 'Sí', 'Hendaya', 2),
('Oier', 'González', '89012345H', '1986', 'Busca un compañero para correr', 'Sí', 'Anglet', 3),
('Miren', 'Etxeberria', '90123456I', '1983', 'Desea un perro tranquilo y cariñoso', 'Sí', 'Irun', 4),
('Iñaki', 'Arana', '01234567J', '1987', 'Quiere adoptar un perro anciano', 'No', 'Hondarribia', 3),
('Eider', 'Goikoetxea', '11223344K', '1980', 'Preferencia por perros pequeños', 'Sí', 'Hossegor', 1),
('Iñigo', 'Uribe', '22334455L', '1982', 'Le gustan los perros de razas grandes', 'Sí', 'Bilbao', 2),
('Naiara', 'Mendizabal', '33445566M', '1985', 'Interesada en perros de terapia', 'No', 'Donostia', 3),
('Ekaitz', 'Larrañaga', '44556677N', '1978', 'Desea adoptar un perro de refugio', 'Sí', 'Vitoria-Gasteiz', 4),
('Xabier', 'Etxeberria', '55667788O', '1984', 'Preferencia por perros jóvenes y juguetones', 'Sí', 'San Sebastián', 3),
('Nora', 'Aguirre', '66778899P', '1981', 'Le gustan los perros grandes y activos', 'No', 'Biarritz', 1),
('Maialen', 'Arrieta', '77889900Q', '1979', 'Busca un perro de raza específica', 'Sí', 'Hendaya', 2),
('Eneko', 'Eguzkiza', '88990011R', '1986', 'Quiere un perro para acompañarle en caminatas', 'Sí', 'Anglet', 3),
('Ainhoa', 'Bilbao', '99001122S', '1983', 'Preferencia por perros de razas pequeñas', 'Sí', 'Irun', 4),
('Izan', 'Santamaría', '00112233T', '1987', 'Le gustaría adoptar un perro mayor', 'No', 'Hondarribia', 3),
('Ane', 'Arana', '11223344U', '1980', 'Preferencia por perros pequeños', 'Sí', 'Hossegor', 1),
('Asier', 'Zubiri', '22334455V', '1982', 'Le gustan los perros grandes y activos', 'Sí', 'Bilbao', 2),
('Maddi', 'Larrazabal', '33445566W', '1985', 'Busca un perro de raza mixta', 'No', 'Donostia', 3),
('Xabi', 'Etxeberria', '44556677X', '1978', 'Desea un perro que se lleve bien con niños', 'Sí', 'Vitoria-Gasteiz', 4),
('Iratxe', 'Irizar', '55667788Y', '1984', 'Le gustan los perros pequeños y juguetones', 'Sí', 'San Sebastián', 3),
('Gorka', 'Etxeberria', '66778899Z', '1981', 'Quiere un perro de raza específica', 'No', 'Bilbao', 1),
('Amaia', 'Etxeberria', '77889900A', '1950', 'Tiene experiencia con perros mayores', 'Sí', 'Donostia', 2),
('Ibai', 'Etxeberria', '88990011B', '1986', 'Desea adoptar un perro de refugio', 'Sí', 'Vitoria-Gasteiz', 3),
('Nerea', 'Etxeberria', '99001122C', '1983', 'Le gustan los perros grandes y activos', 'Sí', 'San Sebastián', 4),
('Eñaut', 'Etxeberria', '00112233D', '1987', 'Prefiere un perro entrenado', 'No', 'Bilbao', 3),
('Haizea', 'Etxeberria', '11223344E', '1980', 'Busca un perro de raza específica', 'Sí', 'Donostia', 1),
('Iñigo', 'Etxeberria', '22334455F', '1982', 'Tiene experiencia con perros pequeños', 'Sí', 'Vitoria-Gasteiz', 2),
('Lur', 'Etxeberria', '33445566G', '1985', 'Preferencia por perros jóvenes', 'No', 'San Sebastián', 3),
('Miren', 'Etxeberria', '44556677H', '1978', 'Desea un perro tranquilo y cariñoso', 'Sí', 'Bilbao', 4),
('Asier', 'Etxeberria', '55667788I', '1984', 'Quiere un perro para hacer ejercicio', 'Sí', 'Donostia', 3),
('Maialen', 'Etxeberria', '66778899J', '1981', 'Le gustan los perros grandes y activos', 'No', 'Vitoria-Gasteiz', 1),
('Olatz', 'Etxeberria', '77889900K', '1979', 'Busca un perro de raza específica', 'Sí', 'San Sebastián', 2),
('Iker', 'Etxeberria', '88990011L', '1986', 'Tiene experiencia con perros mayores', 'Sí', 'Bilbao', 3),
('Amaia', 'Etxeberria', '99001122M', '1983', 'Desea un perro pequeño y amigable', 'Sí', 'Donostia', 4),
('Markel', 'Etxeberria', '00112233N', '1987', 'Preferencia por perros jóvenes', 'No', 'Vitoria-Gasteiz', 3),
('Naroa', 'Etxeberria', '11223344O', '1980', 'Desea adoptar un perro de refugio', 'Sí', 'San Sebastián', 1),
('Aitor', 'Etxeberria', '22334455P', '1982', 'Le gustan los perros grandes y activos', 'Sí', 'Bilbao', 2),
('Maddi', 'Etxeberria', '33445566Q', '1985', 'Tiene experiencia con perros pequeños', 'No', 'Vitoria-Gasteiz', 3),
('Gorka', 'Etxeberria', '44556677R', '1978', 'Preferencia por perros jóvenes', 'Sí', 'San Sebastián', 4),
('Eneko', 'Etxeberria', '55667788S', '1984', 'Desea un perro tranquilo y cariñoso', 'Sí', 'Bilbao', 2);

INSERT INTO tbDogsCandidates (idStaff, idDog, idCandidate, adopDate, comments)
VALUES 
(1, 1, 1, CURDATE(), 'Buena experiencia de adopción'),
(2, 3, 2, CURDATE(), 'Familia amante de los animales'),
(3, 2, 3, CURDATE(), 'Visita al hogar realizada'),
(1, 5, 4, CURDATE(), 'Adopción confirmada por equipo de adopciones'),
(2, 4, 5, CURDATE(), 'Familia con experiencia en cuidado de perros mayores'),
(3, 6, 6, CURDATE(), 'Adoptante con historial de adopciones exitosas'),
(1, 7, 7, CURDATE(), 'Perro y adoptante se llevan bien en las visitas de prueba'),
(2, 8, 8, CURDATE(), 'Adoptante dispuesto a recibir entrenamiento para cuidado especial'),
(3, 9, 9, CURDATE(), 'Adoptante con espacio y tiempo para cuidado del perro'),
(1, 10, 10, CURDATE(), 'Familia comprometida con entrenamiento del perro'),
(2, 11, 11, '2023-10-25', 'Adopción realizada en evento de adopción especial'),
(3, 12, 12, '2023-10-26', 'Familia con experiencia en perros de raza específica'),
(1, 13, 13, '2023-10-27', 'Adoptante con historial de voluntariado en refugios');

/*ALTER TABLE tbCandidates AUTO_INCREMENT = 0;*/
SELECT * FROM tbBreeds;
SELECT * FROM tbDogs;
SELECT * FROM tbCandidates;
SELECT * FROM tbDogsCandidates;
SELECT * FROM tbStaff;
SELECT * FROM tbTypeOfHousing;